window.gamesettings = {
	basescalefactor: 6,
	cameralerpspeed: 0.1,
	slowpanspeed: 100, // in pixels per second
	skycolorday: "#1FAEEB",
	skycolorsunset: ["#1FAEEB", "#E67F7A"],
	entdefaultmovespeed: 500,
	gravity: 2000,
	entdefaultjumppower: 1000,
	entenemyjumppower: 800,
	froggideaththreshold: -1500,
	minclouds: 3,
	maxclouds: 3,
	cloudtop: 40,
	cloudbottom: 150,
	cloudminmovespeed: 20,
	cloudmaxmovespeed: 50,
	windwidth: 15,
	windforce: 500,
	windmarkgeninterval: 50, // interval in milliseconds,
	windmarkspeed: 400,
	windmarkminheight: 5,
	windmarkmaxheight: 5,
	windmarkthreshold: 1500,
	windthreshold: 1080,
	terminalvelocity: 1500,
	offscreenarrowoffset: -20,
	dialogmargin: 100,
	dialogpadding: 40,
	dialogbordercolor: "white",
	dialogcolor: "black",
	dialogtextcolor: "white",
	dialogborderwidth: 10,
	dialogheight: 250,
	dialogendtext: "Press ENTER to continue...",
	dialogtextinterval: 25, // interval in milliseconds
	fallingmushroomanimationlength: 2000, // length in milliseconds
	fallingmushroomanimationcurve: [{x: 0, y: 0}, {x: 1, y: 0}, {x: 1, y: 1}],
	fallingmushroomendingy: -200,
	fallingmushroomendingangle: 90 * Math.PI / 180,
	engineerswitchinterval: 100,
	cutscenemarkheight: 200,
	cutscenemarkalpha: 0.5,
	cutscenemarkanimationlength: 1000,
	cutscenemarkanimationcurve: [{x: 0, y: 0}, {x: 0, y: 1}, {x: 1, y: 1}],
	fadelength: 500,
	walkcycleinterval: 125,
	jumppoint: 30,
	minaifollowdistance: 120
}
