window.gamesettings = {
	basescalefactor: 6,
	cameralerpspeed: 0.1,
	slowpanspeed: 100, // in pixels per second
	skycolor: "#1FAEEB",
	entdefaultmovespeed: 500,
	gravity: 2000,
	entdefaultjumppower: 1000,
	froggideaththreshold: -1500,
	minclouds: 3,
	maxclouds: 3,
	cloudtop: 40,
	cloudbottom: 150,
	cloudminmovespeed: 20,
	cloudmaxmovespeed: 50,
	windwidth: 15,
	windforce: 500,
	windmarkgeninterval: 50, // interval in milliseconds,
	windmarkspeed: 400,
	windmarkminheight: 5,
	windmarkmaxheight: 5,
	windmarkthreshold: 1500,
	windthreshold: 1080,
	terminalvelocity: 1500,
	offscreenarrowoffset: -20
}
