(function() {
	window.texts = [
		"ok so that mf to the right of you is like wind nd it'll propel you upwards :)",
		"uh-oh, looks like the LEAGUE OF MUSHROOM HATERS are getting more mushrooms cut down",
		"they're literally destroying your home. smh my head [insert partially-ironic eye roll emoji]",
		"yk what, you're fed up w this bullshit, you should just kill them bitches",
		"it's time to fight the mushroom haters.",
		"omg hi you look so pretty !! [insert bottom emoji]",
		"ok so this is mushroom land and you're a froggi :))",
		"in a sec you'll be able to use SPACE or W to jump nd then A and D to jump left and right or move while in the air",
		"you can use RIGHT ARROW and LEFT ARROW to stick your tongue out which will be used for attacking later",
		"nd yeah you can hop between mushrooms and stuff so yeah try it ilyyy <3",
		"oh wack you died :((",
		"dw tho you'll just respawn nd it's cool :)",
		"You died...",
		"this is BEN SHAPIRO, he's the first mushroom hater >:(",
		"like his political arguments, his attacks are v uncreative",
		"all he knows how to do is punch.",
		"use your tongue to attack him and avoid his punches",
		"you can do this baby ily :) <3",
		"you lost against ben shapiro lmao",
		"its cool try again ily",
		"AHHH good job baby :)) <3",
		"im so proud of you [insert bottom emoji] !!!",
		"but you're not done yet. there are 2 more mushroom haters to kill.",
		"ew look its ED SHEERAN.",
		"by staying a virgin until 30, ed sheeran gained the power of virginity rays.",
		"he cant punch you, but he will shoot virginity rays at you",
		"if they hit you, you'll take damage. dodge them and hit him as much as you can.",
		"virginity rays fade out as they travel, the further the ray travels the less damage it will deal.",
		"babe its literally ed sheeran, you can do this i believe in you :)",
		"damn. killed by ed sheeran.",
		"retry ig [insert partially-ironic eye roll emoji]",
		"OMG OMG you killed ed sheeran thats so epic !!!",
		"youre the bestest ever :))",
		"now its time for hello kitty saying acab. ew.",
		"anyways you get to have a nice break before the final boss so enjoy that :)",
		"idk i like fucking around in the wind thingies a lot i think its hella fun so if you agree here's a bunch of them :)",
		"okay yeah no hi hi i figured you might want a break before the final boss :)",
		"so yeah hangout w the ghost and relax for a little bit",
		"take as much time as you need here and when you're ready go through the portal on the left ilyyyyyy",
		"this is your break so yeah no you didnt die lets forget that happened ;)"
	];
})();
