(function() {
	window.texts = [
		"The column to the right of you is wind and will force you upwards!",
		"Uh-oh, looks like the LEAGUE OF MUSHROOM HATERS are getting more mushrooms cut down.",
		"These jerks are destroying your home, you have to do something about it!",
		"Yknow what, it's time to take them on.",
		"Let's do this",
		"Hi! :)",
		"This is mushroom land, where you grew up as a frog :)",
		"To move your frog, us A and D for left and right and SPACE to jump.",
		"Use RIGHT ARROW and LEFT ARROW to stick your tongue out which will be used for attacking later.",
		"Hop around between mushrooms and explore!",
		"Looks like you died :(",
		"Don't worry, you'll just respawn!",
		"You died...",
		"This is the first mushroom hater",
		"His attacks are pretty simple",
		"All he knows how to do is punch.",
		"Use your tongue to attack him and avoid his punches",
		"Good luck!",
		"You lost :(",
		"Try again!",
		"Congrats!!",
		"You successfully won against the first mushroom hater.",
		"But you're not done yet. There are 2 more mushroom haters to take on.",
		"This is mushroom hater #2",
		"This mushroom hater has a special power.",
		"He cant punch you, but he can shoot attack rays at you.",
		"If they hit you, you'll take damage. Dodge them and hit him as much as you can.",
		"Attack rays fade out as they travel, the further the ray travels the less damage it will deal.",
		"Good luck!",
		"You lost :(",
		"Try again!",
		"Good job! You won against the second mushroom hater",
		"You're almost ready to fight the final boss!",
		"You've made it this far. You got this!",
		"You get to enjoy a break first though :)",
		"Wind is fun! Enjoy lots of it.",
		"Welcome to your break before the final boss!",
		"Hangout with the ghost and relax for a little bit!",
		"Take as much time as you need here and when you're ready go through the portal on the left :)",
		"Whoops!"
	];
})();
